server:
  port: 8000

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

---
spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/h-audited
#    username: inject argument
#    password: inject argument
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    database: mysql
